### ISSUE TITLE
使用 gforge 生成insert代码报错了。。。

### ISSUE THREAD

**Issue by tangwy01** [caibirdme/gforge#1]
编译的时候提示 
cannot use nil as type int64 in return argument  
是我哪里配置的不对吗
//Insert inserts an array of data into table testTable
func Insert(db *sql.DB, data []map[string]interface{}) (int64, error) {
	if nil == db {
		return nil, errors.New("sql.DB object couldn't be nil")
	}
	cond, vals, err := builder.BuildInsert("testTable", data)
	if nil != err {
		return 0, err
	}
	result, err := db.Exec(cond, vals...)
	if nil != err || nil == result {
		return 0, err
	}
	return result.LastInsertId()
}

**Comment by caibirdme** [comment]
不好意思，由于Github notification太多全部mark as read，没有注意到…现已修复这个问题。
